server:
  port: 8082

spring:
  application:
    name: library-user-service
  datasource:
    url: jdbc:h2:mem:userdb_dev
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    root: INFO
    com.university.library: DEBUG
